environment: production
title: Joah Gerstenberg
email: me@joahg.com
description: ""
keywords: ""
url: "https://www.joahg.com"
basepath: ""
cachebust: ""
thumbnail: "/img/thumbnail.jpg"
# sass:
#   style: compressed
plugins:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - .gitkeep
